### ISSUE TITLE
Add requirements.txt and add .gitignore

### ISSUE THREAD

**Issue by DevHyperCoder** [Rachithooda/Blog-Insider#1]
Please add a `requirements.txt` so others can easily run the code
Also a `.gitignore` file for `*.db` files would be helpful. If required I can add the proposed changes

**Comment by DevHyperCoder** [comment]
Also requesting to change the `SECRET_KEY` incase you are deploying to production :)

**Comment by Rachithooda** [comment]
yeah sure you can open a pull request

**Comment by Rachithooda** [comment]
hey I have made the changes
